name: test

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-24.04-4core-arm64
    strategy:
      matrix:
        database-name:
          - mydb
        database-password:
          - postgres
        database-user:
          - postgres
        database-host:
          - 127.0.0.1
        database-port:
          - 5432
    env:
      RAILS_ENV: test
      TEST_DATABASE_URL: postgres://${{ matrix.database-user }}:${{ matrix.database-password }}@${{ matrix.database-host }}:${{ matrix.database-port }}/${{ matrix.database-name }}
    services:
      postgres:
        image: postgres:16
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: ${{ matrix.database-name }}
          POSTGRES_USER: ${{ matrix.database-user }}
          POSTGRES_PASSWORD: ${{ matrix.database-password }}
        options: --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
      chrome:
        image: browserless/chrome:latest
        ports:
          - 3311:3311
        env:
          PORT: 3311
          CONNECTION_TIMEOUT: 600000
        options: --health-cmd "curl -f http://localhost:3311 || exit 1"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 3
    steps:
      - name: Check out Git Repository
        uses: actions/checkout@v4

      - name: Cache and install APT packages
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libpq-dev
          version: 1.0

      - name: Set up Ruby, Bundler and Rails
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Prepare test environment
        run: |
          bundle exec rails db:test:prepare

      - name: Run all tests
        run: |
          bundle exec rails parallel:spec_full
        env:
          CHROME_URL: http://localhost:3311

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          fail_ci_if_error: false
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload screenshots on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: capybara-screenshots
          path: tmp/capybara
